### ISSUE TITLE
FYI:   python script can be separate file.

### ISSUE THREAD

**Issue by DaveWHarvey** [serverbox/helm-charts#1]
in the data section of the config map, if you use this, it will add all of the files in _files as config map items, you that you can test the python scripts locally as is.

{{ (tpl (.Files.Glob "_files/*").AsConfig . ) | nindent 2 }}

**Comment by timothyclarke** [comment]
@DaveWHarvey Thanks for the tip. Sorry for the slow response, I hasn't seen your comment earlier.  
Is [PR#3](https://github.com/timothyclarke/helm-charts/pull/3) in line with what you were thinking ?

**Comment by DaveWHarvey** [comment]
yes, it is much nicer to edit python in a python editor
